export const COUNTRIES = [
  "Anguilla",
  "Antigua and Barbuda",
  "Argentina",
  "Aruba",
  "Bahamas",
  "Barbados",
  "Belice",
  "Bermuda",
  "Bolivia",
  "Brazil",
  "British Virgin Islands",
  "Canada",
  "Caribbean Netherlands",
  "Cayman Islands",
  "Chile",
  "Colombia",
  "Costa Rica",
  "Cuba",
  "Curaçao",
  "Dominica",
  "Ecuador",
  "El Salvador",
  "Falkland Islands",
  "French Guiana",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guatemala",
  "Guyana",
  "Haiti",
  "Honduras",
  "Jamaica",
  "Martinique",
  "Montserrat",
  "México",
  "Nicaragua",
  "Panamá",
  "Paraguay",
  "Perú",
  "Puerto Rico",
  "República Dominicana",
  "Saint Barthélemy",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Sint Maarten",
  "Suriname",
  "Trinidad and Tobago",
  "Turks and Caicos Islands",
  "Uruguay",
  "Venezuela",
];
